GCC = g++-7 -std=c++17
BINDIR = bin
all: ch2 ch2-1
ch2: ch2-0.cpp
	$(GCC) ch2-0.cpp -o $(BINDIR)/ch2-0
ch2-1: ch2-1.cpp
	$(GCC) ch2-1.cpp -o $(BINDIR)/ch2-1
test: test.cpp
	$(GCC) test.cpp -o $(BINDIR)/test
